name: Pakiranje in objava na DockerHub

on:
  workflow_run:
    workflows: ["Testiranje kode"]
    types:
      - completed

jobs:
  build-and-push:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout kode
        uses: actions/checkout@v3

      - name: Prijava v DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Preveri prijavo
        run: |
          sudo docker info --format '{{.LoggedIn}}' | grep -q "true" || (echo "Prijava v DockerHub ni uspela" && exit 1)

      - name: Zgradi in potisni Docker sliko
        run: |
          sudo docker build -t paskalo4/algoritmi-vaja1:latest .
          sudo docker push paskalo4/algoritmi-vaja1:latest
